name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 8 * * *"

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run setup-postgres
        uses: ./
        id: postgres

      - name: Run tests
        run: |
          python3 -m pip install --upgrade pip pytest psycopg furl
          python3 -m pytest -vv test_action.py
        env:
          CONNECTION_URI: ${{ steps.postgres.outputs.connection-uri }}
          SERVICE_NAME: ${{ steps.postgres.outputs.service-name }}
          EXPECTED_CONNECTION_URI: postgresql://postgres:postgres@localhost:5432/postgres
          EXPECTED_SERVICE_NAME: postgres
          EXPECTED_SERVER_VERSION: "15"
        shell: bash

  parametrized:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        postgres-version:
          - "13"
          - "14"
    steps:
      - uses: actions/checkout@v3

      - name: Run setup-postgres
        uses: ./
        with:
          username: yoda
          password: GrandMaster
          database: jedi_order
          port: 34837
          postgres-version: ${{ matrix.postgres-version }}
        id: postgres

      - name: Run tests
        run: |
          python3 -m pip install --upgrade pip pytest psycopg furl
          python3 -m pytest -vv test_action.py
        env:
          CONNECTION_URI: ${{ steps.postgres.outputs.connection-uri }}
          SERVICE_NAME: ${{ steps.postgres.outputs.service-name }}
          EXPECTED_CONNECTION_URI: postgresql://yoda:GrandMaster@localhost:34837/jedi_order
          EXPECTED_SERVICE_NAME: yoda
          EXPECTED_SERVER_VERSION: ${{ matrix.postgres-version }}
        shell: bash
